StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6A64973C3FE1B9F5}" {
   Id "CDF-Role_AT"
   Target_en_us "AT"
   Target_ru_ru "Гранатомётчик"
   Modified 1784981324
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64973C26976088}" {
   Id "CDF-Role_ATass"
   Target_en_us "ATass"
   Target_ru_ru "Помощник гранатомётчика"
   Modified 1784981366
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64973DF727F970}" {
   Id "CDF-Role_Crewman"
   Target_en_us "Driver"
   Target_ru_ru "Водитель"
   Modified 1784994139
   Author "User"
   LastChanged "Вероника"
  }
  CustomStringTableItem "{6A64973DD438E068}" {
   Id "CDF-Role_CrewmanKO"
   Target_en_us "Gunner"
   Target_ru_ru "Наводчик"
   Modified 1784994128
   Author "User"
   LastChanged "Вероника"
  }
  CustomStringTableItem "{6A649733C3FBD2B0}" {
   Id "CDF-Role_DeputySL"
   Target_en_us "DeputySL"
   Target_ru_ru "Старший стрелок"
   Modified 1784980958
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64CE02BB4CBA8F}" {
   Id "CDF-Role_HeavyCrew"
   Target_en_us "Crew member"
   Target_ru_ru "Член экипажа"
   Modified 1785121946
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64CE011819C6E5}" {
   Id "CDF-Role_HeavyCrewSL"
   Target_en_us "Crew commander"
   Target_ru_ru "Командир экипажа"
   Modified 1785121950
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A649732B2709A04}" {
   Id "CDF-Role_KO"
   Target_en_us "Squad leader"
   Target_ru_ru "Командир отделения"
   Modified 1784980681
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64973DA29DA840}" {
   Id "CDF-Role_LAT"
   Target_en_us "LAT"
   Target_ru_ru "Стрелок-гранатомётчик"
   Modified 1784982048
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64973D0557B640}" {
   Id "CDF-Role_Marksman"
   Target_en_us "Marksman"
   Target_ru_ru "Пехотный снайпер"
   Modified 1784981767
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64973D67A6726C}" {
   Id "CDF-Role_MarksmanRPK"
   Target_en_us "MarksmanRPK"
   Target_ru_ru "Марксман"
   Modified 1784981715
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64973D2DA3C1AB}" {
   Id "CDF-Role_Medic"
   Target_en_us "Medic"
   Target_ru_ru "Медик"
   Modified 1784981804
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64973CF70F2B0C}" {
   Id "CDF-Role_MG"
   Target_en_us "MG"
   Target_ru_ru "Пулемётчик"
   Modified 1784981451
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64973C80927ACC}" {
   Id "CDF-Role_MGass"
   Target_en_us "MGass"
   Target_ru_ru "Помощник пулемётчика"
   Modified 1784981539
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64973C7F133799}" {
   Id "CDF-Role_Rifleman"
   Target_en_us "Rifleman"
   Target_ru_ru "Стрелок"
   Modified 1784981202
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64973D4DDA25E7}" {
   Id "CDF-Role_RiflemanRPK"
   Target_en_us "RiflemanRPK"
   Target_ru_ru "Стрелок-пулемётчик"
   Modified 1784981648
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64973C5D7EB006}" {
   Id "CDF-Role_ZamKomroty"
   Target_en_us "ZamKomroty"
   Target_ru_ru "Заместитель командира роты"
   Modified 1784981154
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A688868434CE9A0}" {
   Id "IMF-Group_Crew"
   Target_en_us "Crew"
   Target_ru_ru "Экипаж техники"
   Modified 1785242554
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A68886B0327ACE1}" {
   Id "IMF-Group_Fireteam"
   Target_en_us "Fireteam"
   Target_ru_ru "Противотанковая группа"
   Modified 1785242270
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A68886D2204FF75}" {
   Id "IMF-Group_Officer"
   Target_en_us "Officer"
   Target_ru_ru "Штаб роты"
   Modified 1785241125
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A68886B97DB2069}" {
   Id "IMF-Group_RifleSquad"
   Target_en_us "RifleSquad"
   Target_ru_ru "Стрелковая группа"
   Modified 1785242406
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A6685860EF53402}" {
   Id "IMF-Role_AT"
   Target_en_us "AT"
   Target_ru_ru "Гранатомётчик"
   Modified 1785123088
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A66858628750FA7}" {
   Id "IMF-Role_ATass"
   Target_en_us "ATass"
   Target_ru_ru "Помощник гранатомётчика"
   Modified 1785123154
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A6685891E5C599D}" {
   Id "IMF-Role_Crew"
   Target_en_us "Crew"
   Target_ru_ru "Экипаж"
   Modified 1785123514
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A66858954BE9E12}" {
   Id "IMF-Role_CrewKO"
   Target_en_us "CrewKO"
   Target_ru_ru "Командир экипажа"
   Modified 1785123490
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A66858652F13310}" {
   Id "IMF-Role_KO"
   Target_en_us "KO"
   Target_ru_ru "Командир отделения"
   Modified 1785122953
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A668584D4BACEBE}" {
   Id "IMF-Role_Komroty"
   Target_en_us "Komroty"
   Target_ru_ru "Командир роты"
   Modified 1785122020
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A668586BFEBD913}" {
   Id "IMF-Role_Marksman"
   Target_en_us "Marksman"
   Target_ru_ru "Снайпер"
   Modified 1785123341
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A668586A30AAD47}" {
   Id "IMF-Role_Medic"
   Target_en_us "Medic"
   Target_ru_ru "Медик"
   Modified 1785123380
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A668586CDF3A6DE}" {
   Id "IMF-Role_MG"
   Target_en_us "MG"
   Target_ru_ru "Пулемётчик"
   Modified 1785123205
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A668586F7C34A8E}" {
   Id "IMF-Role_MGass"
   Target_en_us "MGass"
   Target_ru_ru "Помощник пулемётчика"
   Modified 1785123249
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A66858666665025}" {
   Id "IMF-Role_Rifleman"
   Target_en_us "Rifleman"
   Target_ru_ru "Стрелок"
   Modified 1785123043
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A66858691C66E04}" {
   Id "IMF-Role_RiflemanRPK"
   Target_en_us "RiflemanRPK"
   Target_ru_ru "Стрелок-пулемётчик"
   Modified 1785123300
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A66858795835C90}" {
   Id "IMF-Role_Zamcomroty"
   Target_en_us "Zamcomroty"
   Target_ru_ru "Зам командира роты"
   Modified 1785122857
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A6685867E08911F}" {
   Id "IMF-Role_ZKO"
   Target_en_us "ZKO"
   Target_ru_ru "Зам командира отделения"
   Modified 1785123008
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A68A4062B6F5CC1}" {
   Id "TFC-Group_Crew"
   Target_en_us "Crew"
   Target_ru_ru "Экипаж техники"
   Modified 1785244681
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A68A406709A85EC}" {
   Id "TFC-Group_MotorRifleSquad"
   Target_en_us "MotorRifleSquad"
   Target_ru_ru "Мотострелковое отделение"
   Modified 1785244550
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A68A4018A121DB7}" {
   Id "TFC-Group_Officer"
   Target_en_us "Officer"
   Target_ru_ru "Штаб роты"
   Modified 1785244396
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A68A401CED1A605}" {
   Id "TFC-Group_Riflesquad"
   Target_en_us "Riflesquad"
   Target_ru_ru "Стрелковое отделение"
   Modified 1785244293
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A68834A06F657B1}" {
   Id "TFI-Faction_IMF-UC"
   Target_en_us "IMF"
   Target_ru_ru "Ополченцы"
   Modified 1785234888
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A68834B168F11BA}" {
   Id "TFI-FactionName_IMF"
   Target_en_us "IMF"
   Target_ru_ru "Ополченцы"
   Modified 1785234460
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A688862E8BFF28C}" {
   Id "TFI-Flag_IMF"
   Target_en_us "Flag IMF"
   Target_ru_ru "Флаг ополчения"
   Modified 1785237987
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A6497339D14CC5B}" {
   Id "СDF-Role_Komroty"
   Target_en_us "Komroty"
   Target_ru_ru "Командир роты"
   Modified 1784981073
   Author "User"
   LastChanged "User"
  }
 }
}