StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6A64973C3FE1B9F5}" {
   Id "CDF-Role_AT"
   Target_en_us "AT"
   Target_ru_ru "Гранатомётчик"
   Modified 1784981324
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64973C26976088}" {
   Id "CDF-Role_ATass"
   Target_en_us "ATass"
   Target_ru_ru "Помощник гранатомётчика"
   Modified 1784981366
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64973DF727F970}" {
   Id "CDF-Role_Crewman"
   Target_en_us "Crewman"
   Target_ru_ru "Водитель"
   Modified 1784981918
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64973DD438E068}" {
   Id "CDF-Role_CrewmanKO"
   Target_en_us "CrewmanKO"
   Target_ru_ru "Командир экипажа"
   Modified 1784981971
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A649733C3FBD2B0}" {
   Id "CDF-Role_DeputySL"
   Target_en_us "DeputySL"
   Target_ru_ru "Старший стрелок"
   Modified 1784980958
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A649732B2709A04}" {
   Id "CDF-Role_KO"
   Target_en_us "Squad leader"
   Target_ru_ru "Командир отделения"
   Modified 1784980681
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64973DA29DA840}" {
   Id "CDF-Role_LAT"
   Target_en_us "LAT"
   Target_ru_ru "Стрелок-гранатомётчик"
   Modified 1784982048
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64973D0557B640}" {
   Id "CDF-Role_Marksman"
   Target_en_us "Marksman"
   Target_ru_ru "Пехотный снайпер"
   Modified 1784981767
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64973D67A6726C}" {
   Id "CDF-Role_MarksmanRPK"
   Target_en_us "MarksmanRPK"
   Target_ru_ru "Марксман"
   Modified 1784981715
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64973D2DA3C1AB}" {
   Id "CDF-Role_Medic"
   Target_en_us "Medic"
   Target_ru_ru "Медик"
   Modified 1784981804
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64973CF70F2B0C}" {
   Id "CDF-Role_MG"
   Target_en_us "MG"
   Target_ru_ru "Пулемётчик"
   Modified 1784981451
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64973C80927ACC}" {
   Id "CDF-Role_MGass"
   Target_en_us "MGass"
   Target_ru_ru "Помощник пулемётчика"
   Modified 1784981539
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64973C7F133799}" {
   Id "CDF-Role_Rifleman"
   Target_en_us "Rifleman"
   Target_ru_ru "Стрелок"
   Modified 1784981202
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64973D4DDA25E7}" {
   Id "CDF-Role_RiflemanRPK"
   Target_en_us "RiflemanRPK"
   Target_ru_ru "Стрелок-пулемётчик"
   Modified 1784981648
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64973C5D7EB006}" {
   Id "CDF-Role_ZamKomroty"
   Target_en_us "ZamKomroty"
   Target_ru_ru "Заместитель командира роты"
   Modified 1784981154
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A6497339D14CC5B}" {
   Id "СDF-Role_Komroty"
   Target_en_us "Komroty"
   Target_ru_ru "Командир роты"
   Modified 1784981073
   Author "User"
   LastChanged "User"
  }
 }
}