StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6A64973C3FE1B9F5}" {
   Id "CDF-Role_AT"
   Target_en_us "Anti-Tank"
   Target_ru_ru "Гранатомётчик"
   Modified 1787865967
   Author "User"
   LastChanged "Вероника"
  }
  CustomStringTableItem "{6A64973C26976088}" {
   Id "CDF-Role_ATass"
   Target_en_us "Anti-Tank Assistant"
   Target_ru_ru "Помощник гранатомётчика"
   Modified 1787865987
   Author "User"
   LastChanged "Вероника"
  }
  CustomStringTableItem "{6A64973DF727F970}" {
   Id "CDF-Role_Crewman"
   Target_en_us "Driver"
   Target_ru_ru "Водитель"
   Modified 1784994139
   Author "User"
   LastChanged "Вероника"
  }
  CustomStringTableItem "{6A64973DD438E068}" {
   Id "CDF-Role_CrewmanKO"
   Target_en_us "Gunner"
   Target_ru_ru "Наводчик"
   Modified 1784994128
   Author "User"
   LastChanged "Вероника"
  }
  CustomStringTableItem "{6A649733C3FBD2B0}" {
   Id "CDF-Role_DeputySL"
   Target_en_us "Deputy Squad Leader"
   Target_ru_ru "Старший стрелок"
   Modified 1787865999
   Author "User"
   LastChanged "Вероника"
  }
  CustomStringTableItem "{6A64CE02BB4CBA8F}" {
   Id "CDF-Role_HeavyCrew"
   Target_en_us "Crew member"
   Target_ru_ru "Член экипажа"
   Modified 1785121946
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64CE011819C6E5}" {
   Id "CDF-Role_HeavyCrewSL"
   Target_en_us "Crew commander"
   Target_ru_ru "Командир экипажа"
   Modified 1785121950
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A649732B2709A04}" {
   Id "CDF-Role_KO"
   Target_en_us "Squad leader"
   Target_ru_ru "Командир отделения"
   Modified 1784980681
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A6497339D14CC5B}" {
   Id "CDF-Role_Komroty"
   Target_en_us "Platoon Leader"
   Target_ru_ru "Командир роты"
   Modified 1787866016
   Author "Вероника"
   LastChanged "Вероника"
  }
  CustomStringTableItem "{6A64973DA29DA840}" {
   Id "CDF-Role_LAT"
   Target_en_us "Light Anti-Tank"
   Target_ru_ru "Стрелок-гранатомётчик"
   Modified 1787866026
   Author "User"
   LastChanged "Вероника"
  }
  CustomStringTableItem "{6A64973D0557B640}" {
   Id "CDF-Role_Marksman"
   Target_en_us "Marksman"
   Target_ru_ru "Пехотный снайпер"
   Modified 1784981767
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64973D2DA3C1AB}" {
   Id "CDF-Role_Medic"
   Target_en_us "Medic"
   Target_ru_ru "Медик"
   Modified 1784981804
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64973CF70F2B0C}" {
   Id "CDF-Role_MG"
   Target_en_us "Machine Gunner"
   Target_ru_ru "Пулемётчик"
   Modified 1787866042
   Author "User"
   LastChanged "Вероника"
  }
  CustomStringTableItem "{6A64973C80927ACC}" {
   Id "CDF-Role_MGass"
   Target_en_us "Machine Gunner Assistant"
   Target_ru_ru "Помощник пулемётчика"
   Modified 1787866057
   Author "User"
   LastChanged "Вероника"
  }
  CustomStringTableItem "{6A64973C7F133799}" {
   Id "CDF-Role_Rifleman"
   Target_en_us "Rifleman"
   Target_ru_ru "Стрелок"
   Modified 1784981202
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A64973D4DDA25E7}" {
   Id "CDF-Role_RiflemanRPK"
   Target_en_us "Light Machine Gunner"
   Target_ru_ru "Стрелок-пулемётчик"
   Modified 1787866083
   Author "User"
   LastChanged "Вероника"
  }
  CustomStringTableItem "{6A64973C5D7EB006}" {
   Id "CDF-Role_ZamKomroty"
   Target_en_us "Deputy Platoon Leader"
   Target_ru_ru "Заместитель командира роты"
   Modified 1787866094
   Author "User"
   LastChanged "Вероника"
  }
  CustomStringTableItem "{6A688868434CE9A0}" {
   Id "IMF-Group_Crew"
   Target_en_us "Crewmans"
   Target_ru_ru "Экипаж техники"
   Modified 1787866102
   Author "User"
   LastChanged "Вероника"
  }
  CustomStringTableItem "{6A68886B0327ACE1}" {
   Id "IMF-Group_Fireteam"
   Target_en_us "Fireteam"
   Target_ru_ru "Противотанковая группа"
   Modified 1785242270
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A68886D2204FF75}" {
   Id "IMF-Group_Officer"
   Target_en_us "Officer"
   Target_ru_ru "Штаб роты"
   Modified 1785241125
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A68886B97DB2069}" {
   Id "IMF-Group_RifleSquad"
   Target_en_us "RifleSquad"
   Target_ru_ru "Стрелковая группа"
   Modified 1785242406
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A6685860EF53402}" {
   Id "IMF-Role_AT"
   Target_en_us "Anti-Tank"
   Target_ru_ru "Гранатомётчик"
   Modified 1787866125
   Author "User"
   LastChanged "Вероника"
  }
  CustomStringTableItem "{6A66858628750FA7}" {
   Id "IMF-Role_ATass"
   Target_en_us "Anti-Tank Assistant"
   Target_ru_ru "Помощник гранатомётчика"
   Modified 1787866136
   Author "User"
   LastChanged "Вероника"
  }
  CustomStringTableItem "{6A6685891E5C599D}" {
   Id "IMF-Role_Crew"
   Target_en_us "Crew member"
   Target_ru_ru "Экипаж"
   Modified 1787866147
   Author "User"
   LastChanged "Вероника"
  }
  CustomStringTableItem "{6A66858954BE9E12}" {
   Id "IMF-Role_CrewKO"
   Target_en_us "Crew Leader"
   Target_ru_ru "Командир экипажа"
   Modified 1787866158
   Author "User"
   LastChanged "Вероника"
  }
  CustomStringTableItem "{6A66858652F13310}" {
   Id "IMF-Role_KO"
   Target_en_us "Squad Leader"
   Target_ru_ru "Командир группы"
   Modified 1787866169
   Author "User"
   LastChanged "Вероника"
  }
  CustomStringTableItem "{6A668584D4BACEBE}" {
   Id "IMF-Role_Komroty"
   Target_en_us "Platoon Leader"
   Target_ru_ru "Командир отряда"
   Modified 1787866194
   Author "User"
   LastChanged "Вероника"
  }
  CustomStringTableItem "{6A668586BFEBD913}" {
   Id "IMF-Role_Marksman"
   Target_en_us "Marksman"
   Target_ru_ru "Снайпер"
   Modified 1785123341
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A668586A30AAD47}" {
   Id "IMF-Role_Medic"
   Target_en_us "Medic"
   Target_ru_ru "Медик"
   Modified 1785123380
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A668586CDF3A6DE}" {
   Id "IMF-Role_MG"
   Target_en_us "Machine Gunner"
   Target_ru_ru "Пулемётчик"
   Modified 1787866201
   Author "User"
   LastChanged "Вероника"
  }
  CustomStringTableItem "{6A668586F7C34A8E}" {
   Id "IMF-Role_MGass"
   Target_en_us "Machine Gunner Assistant"
   Target_ru_ru "Помощник пулемётчика"
   Modified 1787866212
   Author "User"
   LastChanged "Вероника"
  }
  CustomStringTableItem "{6A66858666665025}" {
   Id "IMF-Role_Rifleman"
   Target_en_us "Rifleman"
   Target_ru_ru "Стрелок"
   Modified 1785123043
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A66858691C66E04}" {
   Id "IMF-Role_RiflemanRPK"
   Target_en_us "Light Machine Gunner"
   Target_ru_ru "Стрелок-пулемётчик"
   Modified 1787866227
   Author "User"
   LastChanged "Вероника"
  }
  CustomStringTableItem "{6A66858795835C90}" {
   Id "IMF-Role_Zamcomroty"
   Target_en_us "Deputy Platoon Leader"
   Target_ru_ru "Заместитель командира отряда"
   Modified 1787866260
   Author "User"
   LastChanged "Вероника"
  }
  CustomStringTableItem "{6A6685867E08911F}" {
   Id "IMF-Role_ZKO"
   Target_en_us "Deputy Squad Leader"
   Target_ru_ru "Зам командира группы"
   Modified 1787866249
   Author "User"
   LastChanged "Вероника"
  }
  CustomStringTableItem "{6A68A4062B6F5CC1}" {
   Id "TFC-Group_Crew"
   Target_en_us "Crew"
   Target_ru_ru "Экипаж техники"
   Modified 1785244681
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A68A406709A85EC}" {
   Id "TFC-Group_MotorRifleSquad"
   Target_en_us "MotorRifleSquad"
   Target_ru_ru "Мотострелковое отделение"
   Modified 1785244550
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A68A4018A121DB7}" {
   Id "TFC-Group_Officer"
   Target_en_us "Officer"
   Target_ru_ru "Штаб роты"
   Modified 1785244396
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A68A401CED1A605}" {
   Id "TFC-Group_Riflesquad"
   Target_en_us "Riflesquad"
   Target_ru_ru "Стрелковое отделение"
   Modified 1785244293
   Author "User"
   LastChanged "User"
  }
  CustomStringTableItem "{6A68834A06F657B1}" {
   Id "TFI-Faction_IMF-UC"
   Target_en_us "IMF"
   Target_ru_ru "Ополчение"
   Modified 1787866286
   Author "User"
   LastChanged "Вероника"
  }
  CustomStringTableItem "{6A68834B168F11BA}" {
   Id "TFI-FactionName_IMF"
   Target_en_us "IMF"
   Target_ru_ru "Ополченцие"
   Modified 1787866276
   Author "User"
   LastChanged "Вероника"
  }
  CustomStringTableItem "{6A688862E8BFF28C}" {
   Id "TFI-Flag_IMF"
   Target_en_us "Flag IMF"
   Target_ru_ru "Флаг ополчения"
   Modified 1785237987
   Author "User"
   LastChanged "User"
  }
 }
}