SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{6A68A4005D7FBCF2}" {
   m_sEntityPrefab "{955E989C5F6D19C3}Prefabs/Characters/Factions/BLUFOR/CDF/TFC_Character_CDF_Komroty.et"
  }
  SCR_EntityCatalogEntry "{6A68A4005C18BE97}" {
   m_sEntityPrefab "{8DBCA0BE2F71176A}Prefabs/Characters/Factions/BLUFOR/CDF/TFC_Character_CDF_ZamKomroty.et"
  }
  SCR_EntityCatalogEntry "{6A68A40003ED1F75}" {
   m_sEntityPrefab "{66A3470EA1BF1AE3}Prefabs/Characters/Factions/BLUFOR/CDF/TFC_Character_CDF_KO.et"
  }
  SCR_EntityCatalogEntry "{6A68A4000C3E6E32}" {
   m_sEntityPrefab "{FAE1B46F165890A7}Prefabs/Characters/Factions/BLUFOR/CDF/TFC_Character_CDF_ZKO.et"
  }
  SCR_EntityCatalogEntry "{6A68A4000D0332F1}" {
   m_sEntityPrefab "{7C4124E9CCC790CA}Prefabs/Characters/Factions/BLUFOR/CDF/TFC_Character_CDF_Rifleman.et"
  }
  SCR_EntityCatalogEntry "{6A68A4000DB4947F}" {
   m_sEntityPrefab "{3599F74FE00D3286}Prefabs/Characters/Factions/BLUFOR/CDF/TFC_Character_CDF_RiflemanRPK.et"
  }
  SCR_EntityCatalogEntry "{6A68A4000E98B04C}" {
   m_sEntityPrefab "{570731D58612E374}Prefabs/Characters/Factions/BLUFOR/CDF/TFC_Character_CDF_RiflemanPSO.et"
  }
  SCR_EntityCatalogEntry "{6A68A400F3AA910E}" {
   m_sEntityPrefab "{3E1141BDB70D49DD}Prefabs/Characters/Factions/BLUFOR/CDF/TFC_Character_CDF_AT.et"
  }
  SCR_EntityCatalogEntry "{6A68A400F24230F8}" {
   m_sEntityPrefab "{D34C454D9FCB6098}Prefabs/Characters/Factions/BLUFOR/CDF/TFC_Character_CDF_ATass.et"
  }
  SCR_EntityCatalogEntry "{6A68A400081FAE3C}" {
   m_sEntityPrefab "{B4AEF666A0CB4362}Prefabs/Characters/Factions/BLUFOR/CDF/TFC_Character_CDF_MG.et"
  }
  SCR_EntityCatalogEntry "{6A68A400096BB102}" {
   m_sEntityPrefab "{30C97E6A432435F8}Prefabs/Characters/Factions/BLUFOR/CDF/TFC_Character_CDF_MGass.et"
  }
  SCR_EntityCatalogEntry "{6A68A4000A5A5B5E}" {
   m_sEntityPrefab "{2EFAD9BA44475DDD}Prefabs/Characters/Factions/BLUFOR/CDF/TFC_Character_CDF_Marksman.et"
  }
  SCR_EntityCatalogEntry "{6A68A4000AB84924}" {
   m_sEntityPrefab "{F61077665603CA2C}Prefabs/Characters/Factions/BLUFOR/CDF/TFC_Character_CDF_MarksmanRPK.et"
  }
  SCR_EntityCatalogEntry "{6A68A4000B864268}" {
   m_sEntityPrefab "{763A186A4780872A}Prefabs/Characters/Factions/BLUFOR/CDF/TFC_Character_CDF_Medic.et"
  }
  SCR_EntityCatalogEntry "{6A68A400D8328654}" {
   m_sEntityPrefab "{434311284ADE3613}Prefabs/Characters/Factions/BLUFOR/CDF/TFC_Character_CDF_LAT.et"
  }
  SCR_EntityCatalogEntry "{6A68A400D907DE94}" {
   m_sEntityPrefab "{E539F9FA00976C59}Prefabs/Characters/Factions/BLUFOR/CDF/TFC_Character_CDF_Crew.et"
  }
  SCR_EntityCatalogEntry "{6A68A400DA5E407A}" {
   m_sEntityPrefab "{16ECFC348955A8D4}Prefabs/Characters/Factions/BLUFOR/CDF/TFC_Character_CDF_CrewKO.et"
  }
  SCR_EntityCatalogEntry "{6A68A400C2D7AA7C}" {
   m_sEntityPrefab "{B325E4A16D9D1655}Prefabs/Characters/Factions/BLUFOR/CDF/TFC_Character_CDF_HeavyCrewKO.et"
  }
  SCR_EntityCatalogEntry "{6A68A400C3CAB893}" {
   m_sEntityPrefab "{2809FBA68B40215D}Prefabs/Characters/Factions/BLUFOR/CDF/TFC_Character_CDF_HeavyCrew.et"
  }
 }
}