SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{6A68A406D5E262A9}" {
   m_sEntityPrefab "{224360583F4EEC4A}Prefabs/Groups/BLUFOR/CDF/Group_CDF_Officer.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6A68A406D5E262C4}" {
    }
    SCR_EntityCatalogSpawnerData "{6A68A406D5E262CB}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{6A68A406D4216F75}" {
   m_sEntityPrefab "{C954EA3CB2EE3BA9}Prefabs/Groups/BLUFOR/CDF/Group_CDF_MotorRifleSquad.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6A68A406D4216FAB}" {
    }
    SCR_EntityCatalogSpawnerData "{6A68A406D4216FAF}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{6A68A406CBCF401E}" {
   m_sEntityPrefab "{4D4AF13F5C38BA4F}Prefabs/Groups/BLUFOR/CDF/Group_CDF_Riflesquad.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6A68A406CBCF40B6}" {
    }
    SCR_EntityCatalogSpawnerData "{6A68A406CBCF40BA}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{6A68A406C1744018}" {
   m_sEntityPrefab "{269BDC46F5398EAE}Prefabs/Groups/BLUFOR/CDF/Group_CDF_Crew.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6A68A406C17440AC}" {
    }
    SCR_EntityCatalogSpawnerData "{6A68A406C1744097}" {
     m_eSlotTypes 7
    }
   }
  }
 }
}