SCR_FactionHomeTerritoryConfig {
 m_aFactionHomeTerritories {
  SCR_FactionHomeTerritory "{6A68886741B44542}" {
   m_sID "Saint-Philippe"
   m_UIInfo SCR_UIInfo "{6A68886741B4453F}" {
    Name "#AR-MapLocation_StPhillipe"
   }
   m_iWeight 516
  }
  SCR_FactionHomeTerritory "{6A68886741B4453D}" {
   m_sID "Meaux"
   m_UIInfo SCR_UIInfo "{6A68886741B4453A}" {
    Name "#AR-MapLocation_Meaux"
   }
   m_iWeight 43
  }
  SCR_FactionHomeTerritory "{6A68886741B4453B}" {
   m_sID "Tyrone"
   m_UIInfo SCR_UIInfo "{6A68886741B44538}" {
    Name "#AR-MapLocation_Tyrone"
   }
   m_iWeight 7
  }
  SCR_FactionHomeTerritory "{6A68886741B44392}" {
   m_sID "Gravette"
   m_UIInfo SCR_UIInfo "{6A68886741B4439C}" {
    Name "#AR-MapLocation_Gravette"
   }
   m_iWeight 8
  }
  SCR_FactionHomeTerritory "{6A68886741B4439D}" {
   m_sID "Montignac"
   m_UIInfo SCR_UIInfo "{6A68886741B4439E}" {
    Name "#AR-MapLocation_Montignac"
   }
   m_iWeight 210
  }
  SCR_FactionHomeTerritory "{6A68886741B4439F}" {
   m_sID "Lamentin"
   m_UIInfo SCR_UIInfo "{6A68886741B4C91D}" {
    Name "#AR-MapLocation_Lamentin"
   }
   m_iWeight 65
  }
  SCR_FactionHomeTerritory "{6A68886741B4C91A}" {
   m_sID "Le Moule"
   m_UIInfo SCR_UIInfo "{6A68886741B4C901}" {
    Name "#AR-MapLocation_LeMoule"
   }
   m_iWeight 13
  }
  SCR_FactionHomeTerritory "{6A68886741B4C90E}" {
   m_sID "Provins"
   m_UIInfo SCR_UIInfo "{6A68886741B4C90F}" {
    Name "#AR-MapLocation_Provins"
   }
   m_iWeight 8
  }
  SCR_FactionHomeTerritory "{6A68886741B57237}" {
   m_sID "Figari"
   m_UIInfo SCR_UIInfo "{6A68886741B57234}" {
    Name "#AR-MapLocation_Figari"
   }
   m_iWeight 30
  }
  SCR_FactionHomeTerritory "{6A68886741B57235}" {
   m_sID "Chotain"
   m_UIInfo SCR_UIInfo "{6A68886741B57232}" {
    Name "#AR-MapLocation_Chotain"
   }
   m_iWeight 21
  }
  SCR_FactionHomeTerritory "{6A68886741B53F79}" {
   m_sID "Laruns"
   m_UIInfo SCR_UIInfo "{6A68886741B53F7B}" {
    Name "#AR-MapLocation_Laruns"
   }
   m_iWeight 13
  }
  SCR_FactionHomeTerritory "{6A68886741B53891}" {
   m_sID "Morton"
   m_UIInfo SCR_UIInfo "{6A68886741B53890}" {
    Name "#AR-MapLocation_Morton"
   }
   m_iWeight 35
  }
  SCR_FactionHomeTerritory "{6A68886741B538A7}" {
   m_sID "Levie"
   m_UIInfo SCR_UIInfo "{6A68886741B538A6}" {
    Name "#AR-MapLocation_Levie"
   }
   m_iWeight 33
  }
  SCR_FactionHomeTerritory "{6A68886741B538A5}" {
   m_sID "Durras"
   m_UIInfo SCR_UIInfo "{6A68886741B538A4}" {
    Name "#AR-MapLocation_Durras"
   }
   m_iWeight 12
  }
  SCR_FactionHomeTerritory "{6A68886741B5DB35}" {
   m_sID "Vernon"
   m_UIInfo SCR_UIInfo "{6A68886741B5DB32}" {
    Name "#AR-MapLocation_Vernon"
   }
   m_iWeight 16
  }
  SCR_FactionHomeTerritory "{6A68886741B5DB33}" {
   m_sID "Entre-Deux"
   m_UIInfo SCR_UIInfo "{6A68886741B5DB30}" {
    Name "#AR-MapLocation_EntreDeux"
   }
   m_iWeight 17
  }
  SCR_FactionHomeTerritory "{6A68886741CA661E}" {
   m_sID "Régina"
   m_UIInfo SCR_UIInfo "{6A68886741CA661F}" {
    Name "#AR-MapLocation_Regina"
   }
   m_iWeight 28
  }
  SCR_FactionHomeTerritory "{6A68886741CA1F78}" {
   m_sID "Saint-Pierre"
   m_UIInfo SCR_UIInfo "{6A68886741CA1F67}" {
    Name "#AR-MapLocation_StPierre"
   }
   m_iWeight 109
  }
  SCR_FactionHomeTerritory "{6A68886741CA1F66}" {
   m_sID "Beauregard"
   m_UIInfo SCR_UIInfo "{6A68886741CA0FE5}" {
    Name "#AR-MapLocation_Beauregard"
   }
   m_iWeight 8
  }
  SCR_FactionHomeTerritory "{6A68886741CA0FE6}" {
   m_sID "Arleville"
   m_UIInfo SCR_UIInfo "{6A68886741CA0FE7}" {
    Name "#AR-MapLocation_Arleville"
   }
   m_iWeight 8
  }
 }
}