SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSettingExtended "{6A68886703B9A0D9}" {
   m_Info SCR_UIInfo "{6A68886703B9A038}" {
    Name "#TFI-FactionName_IMF"
    Icon "{737EA229B4F5D8C9}UI/Textures/Editor/ContentBrowser/ContentBrowser_Side_Opfor.edds"
   }
   m_Order 100
   m_LabelType FACTION_IMF
   m_LabelGroupType FACTION
   m_eBlackListedModes BUILDING
  }
 }
}