SCR_FactionCallsignInfo {
 m_aCompanyNames {
  SCR_CallsignInfo "{6A6888667D5B2562}" {
   m_sCallsign "#AR-Callsign_FIA_Company_0"
  }
  SCR_CallsignInfo "{6A6888667D5B2555}" {
   m_sCallsign "#AR-Callsign_FIA_Company_1"
  }
  SCR_CallsignInfo "{6A6888667D5B255A}" {
   m_sCallsign "#AR-Callsign_FIA_Company_2"
  }
  SCR_CallsignInfo "{6A6888667D5B2558}" {
   m_sCallsign "#AR-Callsign_FIA_Company_3"
  }
  SCR_CallsignInfo "{6A6888667D5B2559}" {
   m_sCallsign "#AR-Callsign_FIA_Company_4"
  }
  SCR_CallsignInfo "{6A6888667D5B255E}" {
   m_sCallsign "#AR-Callsign_FIA_Company_5"
  }
  SCR_CallsignInfo "{6A6888667D5B255F}" {
   m_sCallsign "#AR-Callsign_FIA_Company_6"
  }
  SCR_CallsignInfo "{6A6888667D5B255C}" {
   m_sCallsign "#AR-Callsign_FIA_Company_7"
  }
 }
 m_aPlatoonNames {
  SCR_CallsignInfo "{6A6888667D5B255D}" {
   m_sCallsign "1"
  }
  SCR_CallsignInfo "{6A6888667D5B2542}" {
   m_sCallsign "2"
  }
  SCR_CallsignInfo "{6A6888667D5B2543}" {
   m_sCallsign "3"
  }
  SCR_CallsignInfo "{6A6888667D5B2540}" {
   m_sCallsign "4"
  }
  SCR_CallsignInfo "{6A6888667D5B2541}" {
   m_sCallsign "5"
  }
  SCR_CallsignInfo "{6A6888667D5B258B}" {
   m_sCallsign "6"
  }
  SCR_CallsignInfo "{6A6888667D5B2588}" {
   m_sCallsign "7"
  }
  SCR_CallsignInfo "{6A6888667D5B2589}" {
   m_sCallsign "8"
  }
  SCR_CallsignInfo "{6A6888667D5B258E}" {
   m_sCallsign "9"
  }
 }
 m_aSquadNames {
  SCR_CallsignInfo "{6A6888667D5B258C}" {
   m_sCallsign "1"
  }
  SCR_CallsignInfo "{6A6888667D5B25F2}" {
   m_sCallsign "2"
  }
  SCR_CallsignInfo "{6A6888667D5B25F3}" {
   m_sCallsign "3"
  }
  SCR_CallsignInfo "{6A6888667D5B25F0}" {
   m_sCallsign "4"
  }
  SCR_CallsignInfo "{6A6888667D5B25F1}" {
   m_sCallsign "5"
  }
 }
 m_sCallsignGroupFormat "%1-%2%3"
 m_sCallsignCharacterFormat "%1-%2%3%4"
 m_sCallsignCharacterWithRoleFormat "%1-%2%3 %4"
 m_aCharacterRoleCallsigns {
  SCR_PlayerLeaderRoleCallsign "{6A6888667D5B25F6}" {
   m_sRoleName "#AR-Role_TeamLeader"
   m_eRoleAvailableForCharacterType PLAYER_ONLY
  }
 }
}