SCR_Faction : "{E7B7EA4823DD81F0}Configs/Factions/BLUFOR.conf" {
 UIInfo SCR_FactionUIInfo "{689B1721666136A5}" {
  Icon "{C051E7DF76161C84}Images/CDF Flag Icon.edds"
 }
 m_bIsCommanderAvailable 0
 m_bCanCaptureBases 0
 m_bCanAIMarkTargets 0
 m_bTasksEnabled 0
 m_CallsignInfo SCR_FactionCallsignInfo "{5DA0F2A6677ADA9E}" : "{CB7824D572DD0D5C}Configs/Callsigns/Callsigns_US.conf" {
 }
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{5C68A0EE815FA292}" : "{346565A34E84681B}Configs/EntityCatalog/CDF/Characters_EntityCatalog_CDF.conf" {
  }
  SCR_EntityCatalogMultiList "{5C9E82F29B327997}" : "{E21683FEC0B6C7B5}Configs/EntityCatalog/CDF/Groups_EntityCatalog_CDF.conf" {
   m_aEntityEntryList {
    SCR_EntityCatalogEntry "{6A68A406D5E262A9}" {
     m_bEnabled 1
    }
    SCR_EntityCatalogEntry "{6A68A406D4216F75}" {
     m_bEnabled 1
    }
    SCR_EntityCatalogEntry "{6A68A406CBCF401E}" {
     m_bEnabled 1
    }
    SCR_EntityCatalogEntry "{6A68A406C1744018}" {
     m_bEnabled 1
    }
   }
  }
 }
}