SCR_Faction : "{E7B7EA4823DD81F0}Configs/Factions/BLUFOR.conf" {
 m_bIsCommanderAvailable 0
 m_bCanCaptureBases 0
 m_bCanAIMarkTargets 0
 m_bTasksEnabled 0
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{5C68A0EE815FA292}" : "{C0ED51F509C92A0A}Configs/EntityCatalog/CDF/Characters_EntityCatalog_knCDF.conf" {
  }
  SCR_EntityCatalogMultiList "{5C9E82F29B327997}" : "{E21683FEC0B6C7B5}Configs/EntityCatalog/CDF/Groups_EntityCatalog_CDF.conf" {
   m_aEntityEntryList {
    SCR_EntityCatalogEntry "{6A68A406D5E262A9}" {
     m_bEnabled 1
    }
    SCR_EntityCatalogEntry "{6A68A406D4216F75}" {
     m_bEnabled 1
    }
    SCR_EntityCatalogEntry "{6A68A406CBCF401E}" {
     m_bEnabled 1
    }
    SCR_EntityCatalogEntry "{6A68A406C1744018}" {
     m_bEnabled 1
    }
   }
  }
 }
}