SCR_Faction : "{277AE7613D88A55B}Configs/Factions/INDFOR.conf" {
 FactionKey "IMF"
 FactionColor 0.44 0 0.0168 1
 UIInfo SCR_FactionUIInfo "{6A68834A5ACF8EC7}" {
  Name "#TFI-FactionName_IMF"
  Icon "{40B12B0DF911B856}UI/Textures/Editor/EditableEntities/Factions/EditableEntity_Faction_USSR.edds"
  m_sNameUpper "#TFI-Faction_IMF-UC"
 }
 "Identity of soldiers" FactionIdentity "{570EEB96B808B7E1}" : "{2BD1C7450E2332A7}Configs/Identities/FactionIdentity_IMF.conf" {
 }
 "Radio encryption key" "RadioIMF"
 m_OutlineFactionColor 0.072 0.001 0.003 1
 m_NotificationFactionColor 0.44 0.01 0 1
 m_NotificationTextFactionColor 0.296 0 0.011 1
 m_bTasksEnabled 0
 m_sFactionFlag "{50824EB9F2C215AB}UI/Textures/Flags/USSR-flag-base-3it.edds"
 m_FactionFlagMaterial "{D33A1334B4A3369D}Assets/Props/Fabric/Flags/Data/Flag_1_2_USSR.emat"
 m_FactionLabel FACTION_IMF
 m_CallsignInfo SCR_FactionCallsignInfo "{60A6B21E18F28741}" : "{BA86BC9CFF5A004B}Configs/Callsigns/Callsigns_IMF.conf" {
 }
 m_iFactionRadioFrequency 43500
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{5C68A0EABE8B7B2A}" : "{68FD78047704406B}Configs/EntityCatalog/FIA/Characters_EntityCatalog_IMF.conf" {
  }
  SCR_EntityCatalogMultiList "{5C68A0EABB80080C}" : "{B938BE16544B480D}Configs/EntityCatalog/FIA/Vehicles_EntityCatalog_IMF.conf" {
  }
  SCR_EntityCatalogMultiList "{5C68A0EAB887A0C4}" : "{BE8E9E59F936EFC5}Configs/EntityCatalog/FIA/Groups_EntityCatalog_IMF.conf" {
  }
  SCR_EntityCatalog "{5C68A0EAA323888C}" : "{1EB41ECC133CE55E}Configs/EntityCatalog/FIA/WeaponTripod_EntityCatalog_IMF.conf" {
  }
  SCR_EntityCatalogMultiList "{5C68C44CB0CFC935}" : "{44605F44BEAA5356}Configs/EntityCatalog/FIA/InventoryItems_EntityCatalog_IMF.conf" {
  }
  SCR_EntityCatalog "{5C9EDDD370331114}" : "{9CD7B9706D751B5A}Configs/EntityCatalog/FIA/SupplyContainerItems_EntityCatalog_IMF.conf" {
  }
 }
 m_FactionHomeTerritoryConfig SCR_FactionHomeTerritoryConfig "{5AEE94D54A52B190}" : "{BE739CEF8657672F}Configs/Identities/Territories/FactionHomeTerritory_IMF.conf" {
 }
}