SCR_EntityCatalogMultiList {
 m_eEntityCatalogType GROUP
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{6A6888662676758B}" {
   m_sEntityPrefab "{306075B25E4CA27D}Prefabs/Groups/INDFOR/Group_IMF_Officer.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6A6888662676758E}" {
    }
    SCR_EntityCatalogSpawnerData "{6A68886626767581}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{6A7694D28DE71C29}" {
   m_sEntityPrefab "{F024E8255A989347}Prefabs/Groups/INDFOR/Group_IMF_RifleSquad.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6A7694D28DE71F57}" {
    }
    SCR_EntityCatalogSpawnerData "{6A7694D28DE71F2C}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{6A7694D281BB56AA}" {
   m_sEntityPrefab "{1DB620D350ACD31D}Prefabs/Groups/INDFOR/Group_IMF_Fireteam.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6A7694D281BB5174}" {
    }
    SCR_EntityCatalogSpawnerData "{6A7694D281BB5176}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{6A7694D283D28BE5}" {
   m_sEntityPrefab "{6079E21A4A1C3E40}Prefabs/Groups/INDFOR/Group_IMF_Crew.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6A7694D283D28BB3}" {
    }
    SCR_EntityCatalogSpawnerData "{6A7694D283D28B8D}" {
     m_eSlotTypes 7
    }
   }
  }
 }
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{6A6888662674430A}" {
   m_sIdentifier "Not Spawned"
  }
 }
}