SCR_MissionHeader {
 World "{BE07DE017DB0F110}Maps/Test World/Test character.ent"
 m_sName "<Insert world name>"
 m_sAuthor "<Insert your name>"
 m_sDescription "<Insert world description>"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
}