SCR_EntityCatalogMultiList {
 m_eEntityCatalogType GROUP
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{6A6888662676758B}" {
   m_sEntityPrefab "{CE41AF625D05D0F0}Prefabs/Groups/INDFOR/Group_FIA_RifleSquad.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6A6888662676758E}" {
    }
    SCR_EntityCatalogSpawnerData "{6A68886626767581}" {
     m_eSlotTypes 7
    }
   }
  }
 }
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{6A6888662674430A}" {
   m_sIdentifier "Not Spawned"
  }
 }
}