SCR_EntityCatalogMultiList {
 m_eEntityCatalogType VEHICLE
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{6A6888662D1CAAD1}" {
   m_sIdentifier " Vehicles"
   m_aEntities {
    SCR_EntityCatalogEntry "{6A6888662D1CAADB}" {
     m_sEntityPrefab "{E28501E93F8EFDC0}Prefabs/Vehicles/Wheeled/UAZ469/UAZ469_FIA_uncovered.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{6A6888662D1CAADA}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{6A6888662D1CAAD8}" {
       m_eSlotTypes VEHICLE_SMALL
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{6A6888662D177DD7}" {
   m_sIdentifier "Helicopters"
  }
 }
}